version: '3.8'

services:
  # --- Tu Web (PHP + Apache) ---
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html # Sincroniza tus cambios al instante
    depends_on:
      - db
    networks:
      - anthropo-net

  # --- Base de Datos (MariaDB) ---
  db:
    image: mariadb:10.4
    restart: always
    environment:
      # Contraseña maestra (para emergencias)
      MYSQL_ROOT_PASSWORD: root
      
      # AQUÍ ESTÁ LA MAGIA: Docker crea esto usando tus datos del .env
      MYSQL_DATABASE: blogdb
      MYSQL_USER: blogmaster
      MYSQL_PASSWORD: juliusDev2025
    volumes:
      - db_data:/var/lib/mysql
      # Importante: Asegúrate que tu archivo SQL se llame así
      - ./blogdb.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - anthropo-net

  # --- phpMyAdmin ---
  pma:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      # Para entrar a phpMyAdmin usa: blogmaster / juliusDev2025
      MYSQL_ROOT_PASSWORD: root 
      UPLOAD_LIMIT: 64M
    depends_on:
      - db
    networks:
      - anthropo-net

volumes:
  db_data:

networks:
  anthropo-net: